packages:
  - docs
catalog:
  '@antfu/eslint-config': ^4.10.1
  '@fontsource/geist-mono': ^5.2.5
  '@pagefind/default-ui': ^1.3.0
  'marked': ^15.0.7
  "@astrojs/starlight": ^0.32.3
  "@types/node": ^22.13.10
  "astro": ^5.5.3
  "bumpp": ^10.1.0
  "eslint": ^9.22.0
  "statl-del": ^0.0.4
  "typescript": ^5.8.2
  "unbuild": ^3.5.0
  "vite": ^6.2.2
  "sharp": ^0.32.5
