packages:
  - docs
catalog:
  '@antfu/eslint-config': ^4.10.1
  '@astrojs/starlight': ^0.32.3
  '@fontsource/geist-mono': ^5.2.5
  '@fontsource/geist-sans': ^5.2.5
  '@pagefind/default-ui': ^1.3.0
  '@types/node': ^22.13.10
  '@unocss/reset': ^66.1.0-beta.6
  astro: ^5.5.3
  bumpp: ^10.1.0
  eslint: ^9.22.0
  eslint-plugin-astro: ^1.3.1
  marked: ^15.0.7
  sharp: ^0.32.5
  statl-del: ^0.0.4
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unocss: ^66.1.0-beta.6
  unocss-preset-animations: ^1.1.1
  vite: ^6.2.2
